### PR TITLE
Add support for MSTest v2

### PR DESCRIPTION
**Pull request by dwalleck**
This is still a WIP, but I wanted to get this out as a reference for discussion. I was torn whether or not to add the MSTestV2 support as a separate repository. MSTestV2 has essentially the same API as the older vstest/MSTest library, but the older vstest library can't be upgraded to support .NET Standard because it requires referencing an assembly rather than a NuGet package for the unit test bits. It may also be worth considering deprecating the existing VsTest unless there's members of the community on < .NET 4.5. I'm completely open to whatever path forward makes the most sense.

### CODE REVIEW

**Comment by dwalleck** [comment]
Hmm, so keeping both projects in one solution breaks because the MSTestV2 project has different build expectations. I'm sure I could modify the build script to take this into account, but that's probably complexity that isn't desirable

**Comment by alexvaluyskiy** [comment]
@dwalleck Is it possible to build a project with VsTest_v1 without VisualStudio? Only with `dotnet.exe`?

**Comment by dwalleck** [comment]
It won't build with just `dotnet` as is because it doesn't look like the dependencies are being restored: https://gist.github.com/dwalleck/9b3aacd60a5aec9498e735540271de1e. I think for that to happen, I'd have to redo its csproj file to the newer style, which breaks (if I remember correctly) because of the assembly reference needed for MSTestV1. I can double check my work to make sure that's the case

**Comment by dwalleck** [comment]
I think I may not have answered your question in my last reply. No, it is not possible to the original plugin without Visual Studio. The original version of VsTest/MSTest comes packaged as an assembly with VS, so there's no reliable way to reference that assembly without including a copy of it in the project.

**Comment by alexvaluyskiy** [comment]
@dwalleck I propose to create a separate repository for MSTestV2 and commit all code there. After that, we will transfer the code into AkkaNetContrib

**Comment by dwalleck** [comment]
That sounds good to me. I'll close this PR and ping you when the new code repo is ready.

**Pull request closed without merging**
